# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
# %pip install tensorflow
import tensorflow as tf

In [4]:
tf.__version__

'2.16.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_csv("./Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values # 불필요한 컬럼 제거
y = dataset.iloc[:, -1].values # Exited

In [6]:
print(dataset.columns[3:-1]) 
print(X)

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(dataset.columns[-1]) 
print(y) # DV

Exited
[1 0 1 ... 1 1 0]


In [8]:
# Check Missing Data

### Encoding categorical data

Label Encoding the "Gender" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [10]:
print(X[:,2])

[0 0 0 ... 0 1 0]


One Hot Encoding the "Geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Geo Index = 1
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X[0])
# Geo One Hot Encoding
# 1.0 0.0 0.0

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [14]:
# ANN 
# Feature Scaling is fundamental
# Even 1, 0 values
# FS is important to Deep Learning

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Scale Everything
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()
# ANN as Sequential layer
# Computational Graph

# tensorflow intergrate with Keras library
# ann artifitial neural network

### Adding the input layer and the first hidden layer

In [19]:
# object of dense class
# 하이퍼파라미터: 뉴런 갯수
# 실험을 통해 뉴런 갯수를 정함: 6개
# relu?
# 옅은 딥러닝
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [21]:
# 하나의 뉴런이 0, 1 을 예측 (바이너리 아웃컴)
# 두개의 뉴런이 A, B, C 를 예측
# 시그모이드 활성 함수? probabiliy

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [22]:
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
# adam: adam optimizer
# binary classification: binary_crossentropy
# non binary classification: categorical_crossentropy


### Training the ANN on the Training set

In [23]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
# hyper parameters
# 32: default value
# 100: number of epochs
# 트레이닝이 될 수록 loss 는 낮아지고 accurary 는 높아진다

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7761 - loss: 0.5934
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7968 - loss: 0.4583
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7979 - loss: 0.4388
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8126 - loss: 0.4252
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8143 - loss: 0.4275
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8314 - loss: 0.4035
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8319 - loss: 0.4111
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8232 - loss: 0.4214
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8223 - loss: 0.4203
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8274 - loss: 0.4158
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8296 - loss: 0.4123
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [24]:
ann.predict(sc.transform([[
  1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000
]]))

# any input of predict method is 2D array
# Geography: France -> Dummy variables: 1, 0, 0
# Male: 1
# Scaling: sc.transform([[...]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[0.07001233]], dtype=float32)

In [25]:
print(ann.predict(sc.transform([[
  1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000
]])) > 0.5)

# False
# Customer doesn't leave the bank

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) # 불린값으로 변경
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1546   49]
 [ 272  133]]


0.8395